### ISSUE TITLE
Scanf function is executed before printf

### ISSUE THREAD

**Issue by alessaba** [holzschu/llvm#1]
Code:
`#include <stdio.h>

int main(){
  printf("Write something: \n");
  char banana[10];
  scanf("%s",banana);
  printf("You typed: %s",banana);
}`

Expected behaviour:
Running this in a regular environment results in the script printing "Write Something:", then wait for user input, then print "You typed:" + what the user typed.
`> ./scanftest  
Write something: Ciao  
You typed: Ciao`

OpenTerm behavior:
Running this in OpenTerm results in the script first waiting for input, then print everything after that.
`iPad Pro di Filippo: lli scanftest.ll 
Ciao
Write something: 
You typed: Ciao`

**Comment by holzschu** [comment]
Well, this is puzzling. I can't reproduce the behavior:

![495eaafd-048e-4cfc-8760-f2dae53ccfe9](https://user-images.githubusercontent.com/8070736/39123682-d8ddaae8-46f8-11e8-9e29-71b8ac95c8d9.jpeg)

**Comment by alessaba** [comment]
‪Are we using the same cfg file and llvm build? I am ‬Using the latest build that’s available here on github.

My cfg file contains this (and works for all my own scripts)
`iPad Pro di Filippo: cat clang.cfg `
`-S -emit-llvm -Wno-nullability-completeness -I ~/usr/include/`

Also, what device do you use to run OpenTerm? mine is the Pro 10.5 if it matters

**Comment by holzschu** [comment]
Found it! It should be fixed with commit a508acc. Let me know.

**Comment by alessaba** [comment]
It gives an error during building

`18/135] Building CXX object tools/lli/CMakeFiles/lli.dir/lli.cpp.o
FAILED: tools/lli/CMakeFiles/lli.dir/lli.cpp.o 
/Users/filippoclaudi2/Downloads/llvm/build_osx/bin/clang++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Itools/lli -I../tools/lli -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/usr/include/libxml2 -Iinclude -I../include -arch arm64 -target arm64-apple-darwin17.5.0 -I/Users/filippoclaudi2/Downloads/llvm/build_osx/include/c++/v1/ -I/Users/filippoclaudi2/Downloads/llvm/../ios_system/ -miphoneos-version-min=11 -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fcolor-diagnostics -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk    -fno-exceptions -fno-rtti -MD -MT tools/lli/CMakeFiles/lli.dir/lli.cpp.o -MF tools/lli/CMakeFiles/lli.dir/lli.cpp.o.d -o tools/lli/CMakeFiles/lli.dir/lli.cpp.o -c ../tools/lli/lli.cpp
../tools/lli/lli.cpp:130:39: error: use of undeclared identifier 'ios_getCommandStatus'
        if (stat_loc) *stat_loc = W_EXITCODE(ios_getCommandStatus(), 0); 
                                             ^
1 error generated.
[23/135] Linking CXX shared library lib/libLLVMBitWriter.dylib
ninja: build stopped: subcommand failed.`

**Comment by holzschu** [comment]
Ah! sorry, I made other changes that depend on iOS_system and forgot to commit these. You'll need the latest version of ios_system.

**Comment by alessaba** [comment]
Perfect! It now works flawlessly. Thanks for your help 😃
