### ISSUE TITLE
Crash on running C++

### ISSUE THREAD

**Issue by ColdGrub1384** [holzschu/llvm#2]
I successfully compiled and ran C code. But, my app crashes when running an `ll` file compiled from C++. C++ is compiled successfully, but not ran.

hellocpp.cpp:

``` c++
#include <iostream>
using namespace std;
int main()  {
    cout << "Hello, World!";
    return 0;
}
```

Environment:

    C_INCLUDE_PATH=/var/containers/Bundle/Application/047E470C-4C72-4713-8C3F-BF2D135507EF/LibTerm.app/usr/lib/clang/include:/var/containers/Bundle/Application/047E470C-4C72-4713-8C3F-BF2D135507EF/LibTerm.app/usr/include
    CPLUS_INCLUDE_PATH=/var/containers/Bundle/Application/047E470C-4C72-4713-8C3F-BF2D135507EF/LibTerm.app/usr/lib/clang/include:/var/containers/Bundle/Application/047E470C-4C72-4713-8C3F-BF2D135507EF/LibTerm.app/usr/include/c++:/var/containers/Bundle/Application/047E470C-4C72-4713-8C3F-BF2D135507EF/LibTerm.app/usr/include

Console:

    $ clang++ -S -emit-llvm 'hellocpp.cpp' -v
    iPad de Adrian $ clang++ -S -emit-llvm 'hellocpp.cpp' -v
    clang version 7.0.0 (https://github.com/llvm-mirror/clang.git 2e0b526f45ace58220a0a371139eaa2c4f62dd62) (https://github.com/llvm-mirror/llvm.git 6d15734d774dd62975dae7e44f42ffd5bfdd2f3c)
    Target: arm64-apple-darwin19.0.0
    Thread model: posix
    InstalledDir: /private/var/mobile/Containers/Data/Application/B4EB5DE2-C22E-4CCE-B9A9-0CB589FEE17B/Documents
     "clang++" -cc1 -triple arm64-apple-ios5.0.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-llvm -disable-free -main-file-name hellocpp.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -faligned-alloc-unavailable -target-cpu generic -target-feature +neon -target-abi darwinpcs -fallow-half-arguments-and-returns -dwarf-column-info -debugger-tuning=lldb -target-linker-version 351.8 -v -coverage-notes-file /private/var/mobile/Containers/Data/Application/B4EB5DE2-C22E-4CCE-B9A9-0CB589FEE17B/Documents/hellocpp.gcno -resource-dir lib/clang/7.0.0 -c-isystem /var/containers/Bundle/Application/DC744DB7-3F9B-4E28-ABFF-6EB8A3ABB9F0/LibTerm.app/usr/lib/clang/7.0.0/include -c-isystem /var/containers/Bundle/Application/DC744DB7-3F9B-4E28-ABFF-6EB8A3ABB9F0/LibTerm.app/usr/include -cxx-isystem /var/containers/Bundle/Application/DC744DB7-3F9B-4E28-ABFF-6EB8A3ABB9F0/LibTerm.app/usr/include/c++/4.2.1 -cxx-isystem /var/containers/Bundle/Application/DC744DB7-3F9B-4E28-ABFF-6EB8A3ABB9F0/LibTerm.app/usr/lib/clang/7.0.0/include -cxx-isystem /var/containers/Bundle/Application/DC744DB7-3F9B-4E28-ABFF-6EB8A3ABB9F0/LibTerm.app/usr/include -fdeprecated-macro -fdebug-compilation-dir /private/var/mobile/Containers/Data/Application/B4EB5DE2-C22E-4CCE-B9A9-0CB589FEE17B/Documents -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=ios-5.0.0 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -o hellocpp.ll -x c++ hellocpp.cpp
    clang -cc1 version 7.0.0 based upon LLVM 7.0.0svn default target arm64-apple-darwin19.0.0
    ignoring nonexistent directory "/usr/include/c++/4.2.1"
    ignoring nonexistent directory "/usr/include/c++/4.2.1/arm64-apple-darwin10/"
    ignoring nonexistent directory "/usr/include/c++/4.2.1/backward"
    ignoring nonexistent directory "/usr/local/include"
    ignoring nonexistent directory "lib/clang/7.0.0/include"
    ignoring nonexistent directory "/usr/include"
    #include "..." search starts here:
    #include <...> search starts here:
     /var/containers/Bundle/Application/DC744DB7-3F9B-4E28-ABFF-6EB8A3ABB9F0/LibTerm.app/usr/include/c++/4.2.1
     /var/containers/Bundle/Application/DC744DB7-3F9B-4E28-ABFF-6EB8A3ABB9F0/LibTerm.app/usr/lib/clang/7.0.0/include
     /var/containers/Bundle/Application/DC744DB7-3F9B-4E28-ABFF-6EB8A3ABB9F0/LibTerm.app/usr/include
    /System/Library/Frameworks (framework directory)
    /Library/Frameworks (framework directory)
    End of search list.
    $ lli 'hellocpp.ll'
    Stack dump:
    0.    Program arguments: lli hellocpp.ll

The crash:

    #15	0x0000000103049ab0 in run_function at /Users/adrianlabbe/Desktop/LibTerm/ios_system_core/ios_system.m:118

    Assertion failed: (isa<GlobalIndirectSymbol>(this)), function isDeclaration, file ../lib/IR/Globals.cpp, line 211.

I defined `clang++` command because I thought it could have something to do, but I see now that passing `clang` as first argument works for C++ files, it does not on my Mac. Anyway, calling `clang` and `clang++` have the same results.

Am I doing something wrong? How I am supposed to compile C++ code?

**Comment by ColdGrub1384** [comment]
I removed `cout << "Hello, World!";` and the code ran.

```c++
#include <iostream>
using namespace std;
int main()  {
    //cout << "Hello, World!";
    return 3;
}
```

    $ clang++ -s -emit-llvm 'hellocpp.cpp'
    $ lli 'hellocpp.cpp'
    $ echo $?
    3

**Comment by holzschu** [comment]
Yes, as I said on Twitter, C++ works except for input and output. The issue is in how `cout` and `cin` are implemented, and how to redirect them to `thread_stout` and `thread_stdin`. 

In practice, this means C++ is not really useable; only C code creates something that can be executed.

**Comment by ColdGrub1384** [comment]
Sorry. I misread, I thought it was only for input.

**Comment by ColdGrub1384** [comment]
Using `printf`, even with C++ works. So, if we really want to use C++, we can. Thank you!
