### ISSUE TITLE
Private APIs

### ISSUE THREAD

**Issue by ColdGrub1384** [holzschu/llvm#3]
I submitted an app with `llvm` to the App Store but it got rejected for Private APIs usage on `libLLVM.framework`:

> Non-public API usage - The app references non-public symbols in Frameworks/libLLVM.framework/libLLVM: _del_curterm, _set_curterm, _setupterm, _tigetnum. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions.

A solution would just be to undefine `HAVE_TERMINFO` macro. https://github.com/llvm-mirror/llvm/blob/dc49f4a5d3cfc950e1b888713833abacb742cc54/lib/Support/Unix/Process.inc#L318

**Comment by holzschu** [comment]
Well spotted.
It seems the best way to undefine `HAVE_TERMINFO` is to define `-DLLVM_ENABLE_TERMINFO=OFF` in the `bootstrap.sh` script (line 104, more or less).

**Comment by ColdGrub1384** [comment]
I will try to compile and see if it works now

**Comment by ColdGrub1384** [comment]
I just compiled and I see the flagged symbols are gone. I will submit to the App Store now and see what happens.

**Comment by ColdGrub1384** [comment]
It worked!
